/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DemoERC20__factory } from "./DemoERC20__factory";
export { GelatoERC20__factory } from "./GelatoERC20__factory";
